inherit_from: .rubocop_todo.yml

#### The following group of customizations is questionable. ####

# We currently exclude types.rb and fetchers.rb because auto-correct results in an
# infinite loop in RuboCop.
AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'lib/cassandra/types.rb'
    - 'lib/cassandra/cluster/schema/fetchers.rb'

# We shouldn't rescue Exception!
Lint/RescueException:
  Exclude:
    - 'lib/cassandra/executors.rb'

#### Good customizations ####

Style/SignalException:
  EnforcedStyle: only_raise

Lint/EndAlignment:
  AutoCorrect: true

Style/IfUnlessModifier:
  MaxLineLength: 90

Style/WhileUntilModifier:
  MaxLineLength: 90

Metrics/LineLength:
  Max: 90
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

# Offense count: 78
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'lib/cassandra/protocol/response.rb'
    - 'lib/cassandra/protocol/responses/event_response.rb'
    - 'lib/cassandra/protocol/responses/result_response.rb'

