ruby:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - jruby
  - rbx-2.2
cassandra:
  - 2.0
  - 2.1
  - 2.2
  - 3.0
  - 3.1
os:asd
  - ubuntu/trusty64
build:
  - type: bundler
    without: development docs
  - script: |
      # Set the Java paths (for CCM)
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH

      # Define Cassandra runtime
      export CASSANDRA_VERSION=$CCM_CASSANDRA_VERSION

      # Create the symlink to the .ccm directory
      ln -s $HOME/.ccm cassandra-logs

      # Run the tests
      bundle exec rake test
      RC = $?

      # Stop Cassandra so that log archiving will be more stable (e.g.
      # Cassandra writes a log while we try to archive, Jenkins throws
      # a fit).
      echo "Shutting down Cassandra cluster"
      ccm stop
      exit $RC
